// <auto-generated />
namespace mvc_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_removeUser_NameCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_removeUser_NameCol));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121804455_v2_removeUser_NameCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
